apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-playground-app-staging
commonLabels:
  env: staging
bases:
- ../../base
configMapGenerator:
- name: argocd-playground-app-config
  literals:
  - ENVIRONMENT=staging
