apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-playground-app-staging

commonLabels:
  env: staging

bases:
- ../../base

resources:
  - namespace.yaml

configMapGenerator:
- name: argocd-playground-app-config
  literals:
  - ENVIRONMENT=staging

patches:
  - path: service-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: argocd-playground-app
