apiVersion: v1
kind: Service
metadata:
  name: argocd-playground-app
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30099
  selector:
    app: argocd-playground-app
  type: NodePort

